# Generated by Django 2.2.5 on 2019-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nivel_hab', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Universo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField(max_length=255)),
                ('universo', models.CharField(max_length=255)),
                ('categoria_heroi', models.CharField(max_length=255)),
                ('habilidade', models.ManyToManyField(to='herois.Habilidade')),
            ],
        ),
    ]
