# Generated by Django 2.2.5 on 2019-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadeVilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nivel_hab', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='heroi',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Vilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('universo', models.CharField(max_length=255)),
                ('habilidadeVilao', models.ManyToManyField(to='herois.HabilidadeVilao')),
            ],
        ),
    ]
