# Generated by Django 2.2.5 on 2019-09-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0002_auto_20190930_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vilao',
            name='habilidadeVilao',
        ),
        migrations.DeleteModel(
            name='HabilidadeVilao',
        ),
        migrations.DeleteModel(
            name='Vilao',
        ),
    ]
