# Generated by Django 2.2.5 on 2019-09-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0003_auto_20190930_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categotia_heroi', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='heroi',
            name='categoria_heroi',
        ),
    ]
